version: '3.8'

services:
  k8s-docker-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.kube:/root/.kube
    environment:
      DOCKER_PROXY_URL: "m.daocloud.io"